"""empty message

Revision ID: bf1d6a557e49
Revises: 
Create Date: 2024-04-03 20:38:22.591459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf1d6a557e49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lisence_plate', sa.String(length=10), nullable=True),
    sa.Column('axle_count', sa.SmallInteger(), nullable=True),
    sa.Column('height', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    # ### end Alembic commands ###
